### ISSUE TITLE
Flatpak version doesn't work since I get freedesktop 22.08 with Mesa 22.1.7

### ISSUE THREAD

**Issue by cold-distance** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#18] opened 2022-09-18 09:34 UTC
Hi, I received the freedesktop 22.08 runtime with Mesa 22.1.7 some weeks ago and MangoHud stop working with Steam. Obviously, Mesa, Steam and MangoHud are in Flatpak format and MangoHud was working correctly with freedesktop 21.08 and Mesa 21.3.9.

I don't if the new version name used by Mesa 22 has something related to this.

![Captura desde 2022-09-17 19-06-33](https://user-images.githubusercontent.com/43167050/190895628-5e46904d-0f98-431b-8c36-fe24b437ddd6.png)

**Comment by gasinvein** [comment] 2022-09-18 09:36
Duplicate of #17

**Closed as not planned by gasinvein** 2022-09-18 09:36 UTC
