### ISSUE TITLE
Doesn't work with steam flatpak on Vulkan games

### ISSUE THREAD

**Issue by zastrixarundell** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#47] opened 2024-03-27 20:02 UTC
Since the 25th of March, mangohud isn't working with steam flatpak. It works with the native version of Steam so I'm opening it here instead of upstream.

The issue might be either on Steam or Mangohud so I'm linking both of the issues.

[Steam flatpak reference](https://github.com/flathub/com.valvesoftware.Steam/issues/1280).

**Comment by slagiewka** [comment] 2024-03-28 18:59
It works with Heroic Games Launcher, so it's likely Steam's Flatpak.

**Comment by jntesteves** [comment] 2024-03-29 18:59
Thanks for reporting this issue. I've been on and off investigating this since it started, but your link saying this also affects VkBasalt helped me figure out this is a Vulkan-Loader issue, and find the potential root cause in Valve's steam-runtime. I've sent PR flathub/com.valvesoftware.Steam/pull/1281 with a workaround on the Steam package, and reported the issue to Valve's steam-runtime.

I'll keep this issue open until a fix is released on one of those packages.

**Comment by jntesteves** [comment] 2024-04-04 01:05
Fixed in Steam stable package on Flathub.

**Closed as completed by jntesteves** 2024-04-04 01:05 UTC
