### ISSUE TITLE
GPU percentage stuck at 0% for ToGL - AMD RX 5500 / Ubuntu 22.04

### ISSUE THREAD

**Issue by fir3-1ce** [flathub/org.freedesktop.Platform.VulkanLayer.MangoHud#28] opened 2023-08-02 15:53 UTC
GPU percentage is stuck at 0% for games that use ToGL, in this case I'm trying CS:GO. It works as intended when I launch with the `-vulkan` parameter.

At first I thought it was an OpenGL issue, because I couldn't open `glxgears` in my terminal. I would get the `can't get libdl.so` prompt when I tried. To fix this, I ended up installing `libqt5pas1_2.10-0` manually via .deb package and then building mangohud from source, but of course this is in my APT list and not the Flatpak environment.

Is there a way to fix this or is ToGL not supported? As stated in the title, I have a Radeon RX 5500 GPU and I'm on Ubuntu 22.04 LTS

**Comment by flightlessmango** [comment] 2023-10-10 00:31
This is bug is likely in mangohud and not in the flatpak, report it there instead [MangoHud](https://github.com/flightlessmango/MangoHud/issues)

**Comment by jntesteves** [comment] 2024-03-12 13:40
I can't reproduce on L4D2 and CS:GO isn't available anymore. I'm closing this issue.

**Closed as not planned by jntesteves** 2024-03-12 13:40 UTC
